name: Auto Labeler - Issues
on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Apply Triage Label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage Requested']
            });